export const ROUTES = {
  HOME: "/",
  ADVISORY: "/advisory",
  ACCREDITATION: "/accreditation",
  APPLY_ACCREDITATION: "/accreditation/apply",
  ABOUT_INSTITUTE: "/about/institute",
  ABOUT_MISSION: "/about/mission",
  ABOUT_POLICIES: "/about/policies",
  ABOUT_ADVISORY: "/about/advisory-board",
  ABOUT_REVIEW: "/about/review-panel",
  CONTACT: "/contact",
  MEMBERSHIP: "/membership",
  REQUEST_ADVISORY_CONSULTATION: "/advisory/request-consultation",
  CERTIFICATION: "/certification",
  PROFESSIONAL_DEVELOPMENT_CATALOGUE: "/professional-development-catalogue",
  APPLY_CERTIFICATION:
    "/professional-development-catalogue/apply-certification",
  COURSE_DETAIL: "/professional-development-catalogue/:id",
  COURSE_STORY_GUIDE: "/professional-development-catalogue/:id/story-guide",
  FULL_MODULE: "/full-module/:id",
  DASHBOARD: "/dashboard",
  DASHBOARD_PROFESSIONAL_DEVELOPMENT: "/dashboard/professional-development",
  DASHBOARD_APPLY_CERTIFICATION:
    "/dashboard/professional-development/apply-certification",
  DASHBOARD_CERTIFICATIONS: "/dashboard/certifications",
  DASHBOARD_COURSES: "/dashboard/courses",
  DASHBOARD_SCHEDULES: "/dashboard/schedules",
  DASHBOARD_CE_TRACKER: "/dashboard/ce-tracker",
  DASHBOARD_ACCREDITATION: "/dashboard/accreditation",
  DASHBOARD_ORDERS_PAYMENTS: "/dashboard/orders-payments",
  DASHBOARD_MEMBERSHIP: "/dashboard/membership",
  DASHBOARD_PROFILE: "/dashboard/profile",
  DASHBOARD_SUBSCRIPTION: "/dashboard/subscription",
  DASHBOARD_ADVISORY_REQUESTS: "/dashboard/advisory-requests",
  LOGIN: "/login",
  SIGNUP: "/signup",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  PAYMENT_SUCCESS: "/payment/success",
  PAYMENT_CANCEL: "/payment/cancel",
  DASHBOARD_COURSE_DETAIL: "/dashboard/courses/:id",
  DASHBOARD_EXAM: "/dashboard/exams/:examId",
  OTHER_PAGE: "/page/:slug",
} as const
